### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by limelect** [neslib/Chet#14]
D10.2.3

clang_gettoken could not be located in libclang.dll

what now?

**Comment by neslib** [comment]
You probably just downloaded Chet.exe from the Release page. The libclang.dll file should be there as well but was missing for some reason and I'm unable to add it.

You could just download the source code form the Release page (for version 1.1) or from the main page (for the current version). You will find the executable and all required DLL's in the Bin directory in the downloaded ZIP file.

Sorry for the confusion. Let me know if this works for you.
