### ISSUE TITLE
Post Processing Support

### ISSUE THREAD

**Issue by jarroddavis68** [neslib/Chet#15]
So, I have been working on adding a feature that can "clean up" the converted header that will compile. After working on this problem for a while, I discovered that, when you manually modify the header, you will be adding, removing, and changing lines. So, wrote some code that will allow you to do this easily and automate the process. 

Next, I added a simple scripting interface over these four routines, and this forms the basis of this modification. I got it integrated tonight and it seems to be working. Yay! I'm gonna tweak it a bit more then figure out how to do a PR, LOL. 

<img width="438" alt="Chet1" src="https://user-images.githubusercontent.com/69952438/162274986-7146a261-b12d-4525-8622-a20c4fb536d9.png">
<img width="781" alt="Chet2" src="https://user-images.githubusercontent.com/69952438/162274991-7b8350c8-ccc6-42e7-9967-00513df922da.png">
<img width="726" alt="Chet3" src="https://user-images.githubusercontent.com/69952438/162274992-0e75104d-5556-4e68-9372-b1230e685917.png">
<img width="435" alt="Chet4" src="https://user-images.githubusercontent.com/69952438/162274995-e0612277-6fa0-4530-8790-67d9b90d9292.png">

**Comment by neslib** [comment]
@jarroddavis68 So no PR then?

**Comment by jarroddavis68** [comment]
I'm reworking it for now, making it more efficient and easier to integrate. Something is going wrong each time I try to add your changes to mine, there are conflicts. I need to figure out how to make the integration so that this will not happen.
