### ISSUE TITLE
Anonymous Unions

### ISSUE THREAD

**Issue by jarroddavis68** [neslib/Chet#16]
PSDL_RWops::(unnamed at C:\Dev\Utils\Chet\projects\SDL\includes\SDL_rwops.h:109:13) = ^SDL_RWops::(unnamed at C:\Dev\Utils\Chet\projects\SDL\includes\SDL_rwops.h:109:13);

I'm getting a lot of these type of things now? Does not seem to handle anonymous unions any longer?

**Comment by neslib** [comment]
This issue was introduced by a new version of libclang. It should be fixed now.
