### ISSUE TITLE
[Question] Why no C++?

### ISSUE THREAD

**Issue by anonimo82** [neslib/Chet#24]
As in subject, why is C++ not supported?

**Comment by neslib** [comment]
This tool is created to integrate with C libraries (DLL's and static libraries). Delphi cannot integrate with C++ libraries, so there is no point in creating a C++ header translator. Furthermore, there are a lot of C++ features that cannot be translated to Delphi.

However, if your goal is to translate some "simple" C++ code to Delphi, then you can use my [Neslib.Clang](https://github.com/neslib/Neslib.Clang) library to give it a go yourself. This library uses the Clang backend to parse C(++) code into an Abstract Syntax Tree, that you can then use to generate Delphi code. You can read more about this in my [libclang for Delphi](https://blog.grijjy.com/2018/05/15/libclang-for-delphi/) blog post.
