### ISSUE TITLE
Post Processing does not work

### ISSUE THREAD

**Issue by michkowalczuk** [neslib/Chet#27]
Hi,
My output pas file contains line starting with `  (* SRCVAL ( papoSource , eSrcType , ii )` and ends with `*)`
I tried to use a few post processing functions:
* `RemoveLineRangeAll("(*", "*)")`
* `RemoveAllLines("  (* SRCVAL", 1)`

but without any effect. Any suggestions?

**Comment by michkowalczuk** [comment]
I found that the order of postprocessing functions matters. 
The following code works:
```
RemoveAllLines("  (* SRCVAL ", 1)
RegEx(...)
RegEx(...)
CreateDynamicImport(0)
```
but this does not:
```
CreateDynamicImport(0)
RegEx(...)
RegEx(...)
RemoveAllLines("  (* SRCVAL ", 1)
```

**Comment by jarroddavis68** [comment]
Hi, is it possible to send me that header you are trying to convert, I will have a look. Thx!

**Comment by michkowalczuk** [comment]
The problem does not occur now, so I'm closing the issue.
