### ISSUE TITLE
PUTF8Char is undeclared

### ISSUE THREAD

**Issue by tim-lebedkov** [neslib/Chet#3]
Error in XE5: PUTF8Char is undeclared

**Comment by tim-lebedkov** [comment]
Chet worked great for the tree-sitter API! Thank you!

**Comment by neslib** [comment]
I am happy to hear Chet worked for you!
I don't really support old compilers, but it looks like you found a workaround for the missing declaration.

If you want to share it, feel free to create a pull request and I will happily merge it into this project.
