### ISSUE TITLE
Add DelayLoading option for external procedure

### ISSUE THREAD

**Issue by ccy** [neslib/Chet#5]
Delphi allow declare external function as [delay loading](http://docwiki.embarcadero.com/CodeExamples/XE7/en/DelayedLoading_(Delphi)).  It would be nice to have an option to specify `delayed` in external procedure declaration.

Example:

```pascal
function GetDesktopWindow: HWND; stdcall; external user32 name 'GetDesktopWindow' delayed;
function GetFooBar: Integer; stdcall; external kernel32 name 'GetFooBar' delayed;
function GetFooBarBar: Integer; stdcall; external 'kernel33' name 'GetFooBarBar' delayed;
```

**Comment by neslib** [comment]
Sorry for the long wait. Added the option now.
